server:
  port: 8080

spring:
  application:
    name: pos

  profiles:
    active: dev  # default

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always