spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 60000

management:
  endpoint:
    health:
      show-details: always

midtrans:
  server-key: dummy-key